// horloge a mots data - file generated by build.rs
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum LED {
    Moins,
    Et,
    DixMin,
    Vingt,
    CinqMin,
    Le,
    Quart,
    Demi,
}
pub static LED_POSITIONS: [(u8, u8); 8] = [
    (0, 2), // Moins
    (0, 3), // Et
    (0, 5), // DixMin
    (1, 4), // Vingt
    (1, 5), // CinqMin
    (1, 2), // Le
    (1, 3), // Quart
    (0, 4), // Demi
];
// ---
pub const NB_HOURS_LED : usize = 0;
pub static HOURS_LED: [[Option<LED>;NB_HOURS_LED];0] = [
];
// ---
pub const NB_MIN5_LED : usize = 3;
pub static MIN5_LED: [[Option<LED>;NB_MIN5_LED];12] = [
    [None, None, None, ],
    [Some(LED::CinqMin), None, None, ],
    [Some(LED::DixMin), None, None, ],
    [Some(LED::Et), Some(LED::Quart), None, ],
    [Some(LED::Vingt), None, None, ],
    [Some(LED::Vingt), Some(LED::CinqMin), None, ],
    [Some(LED::Et), Some(LED::Demi), None, ],
    [Some(LED::Moins), Some(LED::Vingt), Some(LED::CinqMin), ],
    [Some(LED::Moins), Some(LED::Vingt), None, ],
    [Some(LED::Moins), Some(LED::Le), Some(LED::Quart), ],
    [Some(LED::Moins), Some(LED::DixMin), None, ],
    [Some(LED::Moins), Some(LED::CinqMin), None, ],
];
// ---
pub const NB_MINUTES_LED : usize = 0;
pub static MINUTES_LED: [[Option<LED>;NB_MINUTES_LED];0] = [
];
