// horloge a mots data - file generated by build.rs
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum LED {
    L1,
    L2,
    L3,
    L4,
    L5,
    L6,
    L7,
    L8,
}
pub static LED_POSITIONS: [(u8, u8); 8] = [
    (0, 2), // L1
    (1, 2), // L2
    (0, 3), // L3
    (1, 3), // L4
    (0, 4), // L5
    (1, 4), // L6
    (0, 5), // L7
    (1, 5), // L8
];
// ---
pub const NB_HOURS_LED : usize = 0;
pub static HOURS_LED: [[Option<LED>;NB_HOURS_LED];0] = [
];
// ---
pub const NB_MIN5_LED : usize = 11;
pub static MIN5_LED: [[Option<LED>;NB_MIN5_LED];12] = [
    [Some(LED::L1), None, None, None, None, None, None, None, None, None, None, ],
    [Some(LED::L3), None, None, None, None, None, None, None, None, None, None, ],
    [Some(LED::L5), None, None, None, None, None, None, None, None, None, None, ],
    [Some(LED::L7), None, None, None, None, None, None, None, None, None, None, ],
    [Some(LED::L8), None, None, None, None, None, None, None, None, None, None, ],
    [Some(LED::L6), None, None, None, None, None, None, None, None, None, None, ],
    [Some(LED::L4), None, None, None, None, None, None, None, None, None, None, ],
    [Some(LED::L2), Some(LED::L2), Some(LED::L2), Some(LED::L2), None, None, None, None, None, None, None, ],
    [Some(LED::L1), Some(LED::L2), Some(LED::L2), Some(LED::L2), Some(LED::L2), None, None, None, None, None, None, ],
    [Some(LED::L1), Some(LED::L2), Some(LED::L2), Some(LED::L2), Some(LED::L2), Some(LED::L3), Some(LED::L4), None, None, None, None, ],
    [Some(LED::L1), Some(LED::L2), Some(LED::L2), Some(LED::L2), Some(LED::L2), Some(LED::L3), Some(LED::L4), Some(LED::L5), Some(LED::L6), None, None, ],
    [Some(LED::L1), Some(LED::L2), Some(LED::L2), Some(LED::L2), Some(LED::L2), Some(LED::L3), Some(LED::L4), Some(LED::L5), Some(LED::L6), Some(LED::L7), Some(LED::L8), ],
];
// ---
pub const NB_MINUTES_LED : usize = 0;
pub static MINUTES_LED: [[Option<LED>;NB_MINUTES_LED];0] = [
];
