[package]
name = "horloge"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"
lto = true
opt-level = "s"

[dependencies]
embedded-hal = "0.2"

# Panic behaviour, see https://crates.io/keywords/panic-impl for alternatives
panic-halt = "0.2"

[dependencies.atmega-hal]
git = "https://github.com/Rahix/avr-hal"
features = ["atmega328p"]

[features]
default = ["big_panel"]
big_panel=[]
mini_panel=[]